services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: jobs_north_db
    environment:
      - POSTGRES_DB=jobs_north
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
